import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:line_it_up/custom_widgets/custom_widgets.dart';
import 'package:line_it_up/notification/view/view.dart';
import 'package:line_it_up/root/view/view.dart';
import 'package:line_it_up/user_home/view/view.dart';
import 'package:line_it_up/user_line_skipper/cubit/line_skipper_cubit.dart';
import 'package:line_it_up/user_line_skipper/widgets/widgets.dart';
import 'package:line_it_up/utils/utils.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
// import 'package:mobile_scanner/mobile_scanner.dart';

part 'line_skipper_page.dart';
part 'confirm_location_page.dart';
part 'order_list_page.dart';
part 'finding_line_skipper_page.dart';
part 'finding_order_page.dart';
part 'scan_qr_page.dart';
part 'line_skipper_payment_page.dart';
part 'payment_success_page.dart';
